### ISSUE TITLE
Bookdown docs folder

### ISSUE THREAD

**Issue by rosstox26** [Ameybhile/MBAn_Career_Handbook#1]
Two quick things:

Your bookdown content should be on the root rather than inside the sub-folder
You need to publish to the "docs" folder for GitHub to recognize where to get the published version from. Refer to section 6.3 https://bookdown.org/yihui/bookdown/github.html

**Comment by rosstox26** [comment]
Look at the folder structure here: https://github.com/gthuiz/MBAnCareerPulse 

Right now your content is inside a folder rather than on the root.

**Comment by rosstox26** [comment]
I see that your folder structure is now aligned with what I was looking for. Thanks. Good Job.

However, I am unable to access your published site. It should be at https://ameybhile.github.io/MBAn_Career_Handbook but its not showing up for me.

**Comment by rosstox26** [comment]
I tried to resolve the issue by removing the .nojackyll file - but that did not help.

**Comment by marysilvio** [comment]
Updated repository publishing settings to resolve
